Repository CubingRF/wca-regulations-translations, pull requests merged in 2023-01, with the labels that each got.

#133 Изменение ссылки на репозиторий
  russian/wca-regulations.md
Labels: техническое

#126 Положения 2023-01-01: Исправления по использованию определений, связанных с таймерами
  russian/wca-guidelines.md
  russian/wca-regulations.md
Labels: 2023-01-01

#134 Положения 2023-02-01: Капитализация X и Y, используемых как переменные
  russian/wca-guidelines.md
  russian/wca-regulations.md
Labels: 2023-02-01

#135 Положения 2023-02-01: Изменение формулировки 2i1c+
  russian/wca-guidelines.md
Labels: 2023-02-01

#138 Положения 2023-02-01: Расширение 2a3
  russian/wca-regulations.md
Labels: 2023-02-01

#140 Положения 2023-02-01: Clock
  russian/wca-guidelines.md
  russian/wca-regulations.md
Labels: 2023-02-01

#141 Положения 2023-02-01: Определение окончания соревнований
  russian/wca-guidelines.md
  russian/wca-regulations.md
Labels: 2023-02-01

#143 Положения 2023-02-01: Добавление уточнения для попыток, когда судья забывает установить непрозрачный объект в слепой сборке
  russian/wca-guidelines.md
Labels: 2023-02-01

#142 Положения 2023-02-01: Добавление 1h+++
  russian/wca-guidelines.md
Labels: 2023-02-01

#146 Положения 2023-02-01: Добавление уточнения по записи результата Мульти-блайнда
  russian/wca-guidelines.md
Labels: 2023-02-01

#147 Положения 2023-02-01: Добавление 4g2 для кнопок Clock'а
  russian/wca-guidelines.md
  russian/wca-regulations.md
Labels: 2023-02-01

#149 Положения 2023-02-01: Определение хода
  russian/wca-guidelines.md
  russian/wca-regulations.md
Labels: 2023-02-01

#152 Положения 2023-02-01: Изменения в 11e++...
  russian/wca-guidelines.md
  russian/wca-regulations.md
Labels: 2023-02-01

#154 Капитализация после `Исключение:`
  russian/wca-regulations.md
Labels: грамматика

#153 Фикс наименований КХ и МБЛД
  russian/wca-guidelines.md
  russian/wca-regulations.md
Labels: определения

#156 `по решению`, `по усмотрению` - `на усмотрение`
  russian/wca-guidelines.md
  russian/wca-regulations.md
Labels: единообразие

#139 Положения 2023-02-01: Определение элемента в 5b6
  russian/wca-regulations.md
Labels: 2023-02-01

#148 Положения 2023-02-01: Добавление исключения в 9l
  russian/wca-regulations.md
Labels: 2023-02-01

#159 Положения 2023-02-01: Остановка попытки сразу после нарушения положения, ведущего к её дисквалификации
  russian/wca-regulations.md
Labels: 2023-02-01

#155 Фикс наименований ОХ и БЛД
  russian/wca-guidelines.md
  russian/wca-regulations.md
Labels: единообразие

#123 Положения 2023-02-01: Общение во время попытки кх
  russian/wca-regulations.md
Labels: 2023-02-01
